"""empty message

Revision ID: 447dcdd49af9
Revises: f713692b8164
Create Date: 2021-05-06 23:43:27.598819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '447dcdd49af9'
down_revision = 'f713692b8164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('ans', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stage')
    )
    op.create_table('attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('of', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=True),
    sa.Column('atmpts', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['of'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('uptime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('submission', sa.Column('ans', sa.String(), nullable=False))
    op.add_column('submission', sa.Column('correct', sa.Integer(), nullable=True))
    op.add_column('submission', sa.Column('review', sa.String(), nullable=True))
    op.add_column('submission', sa.Column('stage', sa.Integer(), nullable=False))
    op.add_column('submission', sa.Column('sub', sa.String(), nullable=False))
    op.add_column('submission', sa.Column('time', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('notif_count', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('upgrade_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'upgrade_time')
    op.drop_column('user', 'notif_count')
    op.drop_column('submission', 'time')
    op.drop_column('submission', 'sub')
    op.drop_column('submission', 'stage')
    op.drop_column('submission', 'review')
    op.drop_column('submission', 'correct')
    op.drop_column('submission', 'ans')
    op.drop_table('stats')
    op.drop_table('notification')
    op.drop_table('attempts')
    op.drop_table('answer')
    op.drop_table('announcement')
    # ### end Alembic commands ###
